import React from 'react';

const Home = () => (
    <main className="home">
        <h1>Home</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum consectetur dolor dolor, a mollis nunc congue quis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur gravida orci sed accumsan lacinia. Praesent aliquet tortor eget justo mollis aliquam. Nulla lacinia, turpis ac facilisis laoreet, nisi purus tincidunt nisl, id convallis massa massa non mi. Aenean a neque nec ipsum maximus mollis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed a tellus a purus sagittis fringilla ac nec tortor. Sed sagittis molestie posuere. Suspendisse fermentum fermentum nulla, eu vestibulum mi vulputate ac. Nullam vulputate finibus nunc vel lacinia. Vivamus mattis risus quam, ut pellentesque erat varius eu. Donec nec iaculis orci. In non lorem non sapien hendrerit auctor in in dolor. Proin elementum eget sem vel consequat. Donec felis est, tincidunt quis euismod ornare, interdum in purus.</p>
        <p>Cras mattis interdum arcu vel aliquam. Integer lacinia eros tortor, sit amet mattis metus sagittis eu. Ut nec luctus enim. Aliquam cursus nulla quis pulvinar accumsan. Curabitur a finibus sapien, nec placerat turpis. Proin lacus erat, varius id dui sed, malesuada gravida ex. Suspendisse gravida dolor id auctor lacinia. Suspendisse eget est fermentum, elementum neque dictum, laoreet sapien. Aliquam pulvinar urna eu semper pretium.</p>
        <p>Maecenas sem nisl, laoreet placerat tincidunt eget, bibendum vitae nisi. Maecenas ut leo non justo convallis faucibus nec eget purus. Aliquam erat volutpat. Aliquam vel metus accumsan, lacinia sapien vel, accumsan felis. Morbi auctor euismod dolor, a posuere diam sodales non. Nulla pharetra, enim quis dignissim accumsan, elit turpis mollis neque, et venenatis velit urna at odio. Maecenas tellus tortor, dapibus porta blandit a, consectetur in lectus. Nulla et odio id felis viverra vehicula. Curabitur sed tortor vel ligula placerat ullamcorper. Nulla facilisis arcu a nisl feugiat euismod. Etiam lectus libero, molestie in sollicitudin ut, efficitur vel tortor. Mauris quis nibh eget magna rhoncus venenatis vel sed orci. Nulla facilisi. In sit amet ligula egestas, tempus sem ac, ultrices sapien.</p>
        <p>Curabitur vel pretium purus. Aenean posuere dictum sollicitudin. Aliquam tristique tempor convallis. Sed dapibus nisi quis metus consectetur varius. Morbi ac ligula sed nisi pellentesque rutrum a in purus. Praesent suscipit diam vel velit iaculis, non euismod ligula euismod. Praesent tempus enim a lorem finibus bibendum.</p>
        <p>Vestibulum eleifend, quam ut ultrices rutrum, diam orci fringilla metus, et varius ex dolor vel elit. Integer eu lorem arcu. Fusce dignissim, nisi id auctor semper, tellus quam consectetur erat, et elementum lectus risus sed urna. Pellentesque ac ornare purus. Nulla tincidunt velit nibh, ut consectetur dolor aliquet nec. Nunc vel neque eget diam vestibulum faucibus eget nec urna. Praesent aliquet lacinia sem non tempus. Sed dolor magna, tristique ut posuere ac, facilisis in dolor. Maecenas tincidunt massa sed dolor tempor, ut feugiat magna tempus.</p>
    </main>
);

export default Home;